# MidiPunk routing configuration file
## Multiple configurations can be created and loaded via the API or web interface.

## The label is a human-readable name for the configuration.
label: "Example Route"
## Set the logging level for the route. This controls the verbosity of log messages.
## Options are: "NONE", "ERROR", "INFO", "DEBUG", "ALL"
## Any log level above "INFO" may producte a large volume of log messages,
## and may impact overall performance and timing of MIDI messages.
logLevel: "NONE" # none, error, warn, info, debug, all
## Set the MIDI program number (1-128) to send to connected devices on load,
## or which program change message should load this configuration.
## Leave blank to disable program change handling (manual mode).
programNumber: 1
## Ports define the available MIDI input and output devices for use in routes.
## Each port must have a unique `id`.
## `type` can be "USB" or "DIN".
## `direction` can be "INPUT" or "OUTPUT".
## `label` is a human-readable name for the port.
## For DIN ports, `device` specifies the system device path.
## A port must be defined here before it can be used in a route.
ports:
  - id: "1"
    type: "USB"
    direction: "INPUT"
    label: "88 Keys In"
  - id: "2"
    type: "USB"
    direction: "OUTPUT"
    label: "JT-4000 Output"
  - id: "3"
    type: "USB"
    direction: "OUTPUT"
    label: "ARGON8M Output"
  - id: "din1"
    type: "DIN"
    device: "/dev/ttyAMA2"
    direction: "INPUT"
    label: "SQ-64 In"
## Routes define how MIDI messages are routed from inputs to outputs.
## If `channel` is specified, only messages to/from that channel are routed on that port.
## If `channel` is omitted, messages are routed to/from all channels on that port.
routes:
  - label: "88 Keys to JT-4000"
    enabled: true
    inputs:
      - portId: "1"
      - portId: "din1"
    outputs:
      - portId: "2"
        channel: 2
      - portId: "3"
        channel: 2
